//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masks
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_s_import
    {
        public int Id { get; set; }
        public string Наименование_продукции { get; set; }
        public Nullable<int> Артикул { get; set; }
        public Nullable<decimal> Минимальная_стоимость_для_агента { get; set; }
        public string Изображение { get; set; }
        public string Тип_продукции { get; set; }
        public Nullable<int> id_type_products { get; set; }
        public Nullable<int> Количество_человек_для_производства { get; set; }
        public Nullable<int> Номер_цеха_для_производства { get; set; }
        public Nullable<int> Id_products { get; set; }
        public Nullable<int> Id_materials { get; set; }
    
        public virtual id_type_products id_type_products1 { get; set; }
        public virtual materials_short_s_import materials_short_s_import { get; set; }
        public virtual product_materials product_materials { get; set; }
    }
}
