//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masks
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_materials()
        {
            this.products_s_import = new HashSet<products_s_import>();
        }
    
        public int Id { get; set; }
        public string Продукция { get; set; }
        public string Наименование_материала { get; set; }
        public Nullable<int> Id_name_materials { get; set; }
        public Nullable<int> Необходимое_количество_материала { get; set; }
    
        public virtual id_Product_materials id_Product_materials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products_s_import> products_s_import { get; set; }
    }
}
